### ISSUE TITLE
Haftada 1 bağlantı kurulamadı hatası alıyorum

### ISSUE THREAD

**Issue by devartist** [teknomavi/tcmb#6]
7-8 farklı websitesinde kullanıyorum ortalama günlük 10.000 arası request yapılıyordur. Ortalama haftada bir sefer bu hatayı alıyorum. Tüm websitelerimde alıyorum bu hatayı ve yaklaşık yarım saat ekadar bağlantı kurulamıyor. Sonra kendi kendine düzeliyor. 

İlgilenirseniz sevinirim

```
Fatal error: Uncaught exception 'Teknomavi\Tcmb\Exception\ConnectionFailed' with message 'Sunucu Bağlantısı Kurulamadı: Maximum (20) redirects followed' in /home/atombarkod/public_html/vendor/teknomavi/tcmb/src/Doviz.php:94 
Stack trace: 
#0 /home/atombarkod/public_html/vendor/teknomavi/tcmb/src/Doviz.php(198): Teknomavi\Tcmb\Doviz->getTcmbData() 
#1 /home/atombarkod/public_html/vendor/teknomavi/tcmb/src/Doviz.php(181): Teknomavi\Tcmb\Doviz->getCurrencyExchangeRate('USD', 'ForexSelling') 
#2 /home/atombarkod/public_html/app/controller/BaseController.php(109): Teknomavi\Tcmb\Doviz->kurSatis('USD') 
#3 /home/atombarkod/public_html/app/controller/OrderController.php(81): Controller\BaseController->setMasterSettings('admin') 
#4 [internal function]: Controller\OrderController->make('/admin/orders', Array) 
#5 /home/atombarkod/public_html/app/library/Route.php(107): call_user_func(Array, '/admin/orders', Array) 
#6 /home/atombarkod/public_html/app/routes.php(457): Library\Route->submit() 
#7 /home/atombarkod/public_html/index.php(1 in /home/atombarkod/public_html/vendor/teknomavi/tcmb/src/Doviz.php on line 94
```

**Comment by GoktugOzturk** [comment]
bir şekilde veriye ulaşamayıp redirect loop'a giriyor gibi görünüyor. 20 seferden sonra da exception ile çıkıyor koddan. Sebebi hakkında aklıma gelen tek sebep tam yenilenme zamanına gelmesi olabilir. Onun için kodda bir tampon süre eklemiştim ama diyecek birşeyim yok.
